### ISSUE TITLE
Uncaught Error: Call to a member function get_custom_fields() on null

### ISSUE THREAD

**Issue by vlasscontreras** [vlasscontreras/gragrid#15]
After the update to Gravity Forms 2.5, [some users](https://wordpress.org/support/topic/fatal-error-3874/#post-14468753) started to report issues with Gragrid.

## How to reproduce

1. Install Gravity Forms `^2.5`
2. Install Gragrid 2.1 or lower
3. Set up an API key
4. Create a form
5. Attempt to create a SendGrid feed

## Exception/Stacktrace

```
Fatal error: Uncaught Error: Call to a member function get_custom_fields() on null in /wp-content/plugins/gragrid/class-gragrid.php:473 

Stack trace:
#0 /wp-content/plugins/gragrid/class-gragrid.php(220): Gragrid->sengrid_custom_fields_map() 
#1 /wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(1579): Gragrid->feed_settings_fields() 
#2 /wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(1297): GFFeedAddOn->get_feed_settings_fields() 
#3 /wp-includes/class-wp-hook.php(292): GFFeedAddOn->feed_settings_init('') 
#4 /wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) 
#5 /wp-includes/plugin.php(484): WP_Hook->do_action(Array) 
#6 /wp-settings.php(560): do_action('init') 
#7 /wp-config.php(96): require_once('/w...') 
#8 /wp-load.php(37): require_once('/w...') 
#9 /wp-admin/admin.php(34): require_once('/var/w in /wp-content/plugins/gragrid/class-gragrid.php on line 473

```

Initial inspection indicates that the reason might be related to the new Settings API.

**Comment by vlasscontreras** [comment]
Fixed in #16
